### ISSUE TITLE
Thanks for sharing

### ISSUE THREAD

**Issue by bmcandr** [scottyhq/share-a-map#1]
Hey @scottyhq, this repo popped up in my feed and I thought it was pretty cool! I was inspired to build on the idea by throwing STAC and GitHub Actions into the mix. The result: a periodically updating map displaying a ~recent Sentinel-2 true color image that intersects a randomly selected National Park that updates every 6 hours.

https://github.com/bmcandr/stac-tile-map

**Comment by scottyhq** [comment]
Awesome, good to hear from you @bmcandr, those additions are great! Reminds me a bit of https://github.com/wildtreetech/sentinel2-bot but with the bonus of interactivity :)
